#ifndef GDA_GDAA_ASSETS_H
#define GDA_GDAA_ASSETS_H

#include <tonc.h>

typedef enum {
    GDAA_TRACK_BACK_ON_TRACK = 0,
    GDAA_TRACK_BASE_AFTER_BASE = 1,
    GDAA_TRACK_BASH = 2,
    GDAA_TRACK_BLAST_PROCESSING = 3,
    GDAA_TRACK_CANT_LET_GO = 4,
    GDAA_TRACK_CHAOZ_IMPACT = 5,
    GDAA_TRACK_CLOWNPARTY_REMIX = 6,
    GDAA_TRACK_CLUBSTEP = 7,
    GDAA_TRACK_CLUTTERFUNK = 8,
    GDAA_TRACK_CYCLES = 9,
    GDAA_TRACK_DEADLOCKED = 10,
    GDAA_TRACK_DEATH_MOON = 11,
    GDAA_TRACK_DRY_OUT = 12,
    GDAA_TRACK_ELECTRODYNAMIX = 13,
    GDAA_TRACK_ELECTROMAN_ADVENTURES = 14,
    GDAA_TRACK_ENIGMA = 15,
    GDAA_TRACK_EVERY_END = 16,
    GDAA_TRACK_FINAL_BATTLE = 17,
    GDAA_TRACK_FIRE_AURA = 18,
    GDAA_TRACK_GHOST_OF_JUPITER = 19,
    GDAA_TRACK_GOLDEN_HAZE = 20,
    GDAA_TRACK_HEXAGON_FORCE = 21,
    GDAA_TRACK_INFERNOPLEX = 22,
    GDAA_TRACK_JUMPER = 23,
    GDAA_TRACK_MENU_THEME = 24,
    GDAA_TRACK_POLARGEIST = 25,
    GDAA_TRACK_PROBLEMATIC = 26,
    GDAA_TRACK_ROSE = 27,
    GDAA_TRACK_SELECT_PAYMENT_TYPE = 28,
    GDAA_TRACK_STAY_INSIDE_ME = 29,
    GDAA_TRACK_STEREO_MADNESS = 30,
    GDAA_TRACK_STEREO_MADNESS_2 = 31,
    GDAA_TRACK_THEORY_OF_EVERYTHING = 32,
    GDAA_TRACK_THEORY_OF_EVERYTHING_2 = 33,
    GDAA_TRACK_TIME_MACHINE = 34,
    GDAA_TRACK_ULTIMATE_DESTRUCTION = 35,
    GDAA_TRACK_XSTEP = 36,
    GDAA_TRACK_COUNT = 37,
    GDAA_TRACK_INVALID = 0xFFFF
} GdaaTrackId;
typedef struct { const u8* data; u32 size; u32 stored_source_start_ms; } GdaaAsset;
extern const GdaaAsset gdaa_assets[GDAA_TRACK_COUNT];
static inline const GdaaAsset* gdaa_asset_get(GdaaTrackId t){return t < GDAA_TRACK_COUNT ? &gdaa_assets[t] : NULL;}
#endif
